### ISSUE TITLE
Website down

### ISSUE THREAD

**Issue by annahowell** [lab-dev-code/grav-theme-identity#4]
Hi, just to let you know that:

http://lab.dev-code.fr/demos/grav-themes/identity

Appears to be down :)

**Comment by lab-dev-code** [comment]
Hi !

Thanks for this remark, but in fact it's a "normal" situation.
This account and the dev-code.fr domain referred to a small developers team which does not exist anymore.

Repositories will probably be transferred to the main developer @antoine-duchenet.
I'm pretty sure he will be able to help anyone needing  demos of our little projects.
